dist: xenial

addons:
  apt:
    packages: 
     - ffmpeg libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev
     - autoconf automake clang clang-3.8 libtool pkg-config build-essential
     - libarchive-dev
     - python-qt4
    update: true

before_install:
 - sudo pip install --upgrade pip>=19.0
 - curl -LO https://github.com/zeromq/libzmq/releases/download/v4.3.1/zeromq-4.3.1.tar.gz
 - tar xfz zeromq-4.3.1.tar.gz
 - cd zeromq-4.3.1
 - ./autogen.sh
 - ./configure CPPFLAGS=-DPIC CFLAGS=-fPIC CXXFLAGS=-fPIC LDFLAGS=-fPIC --disable-shared --enable-static
 - make
 - sudo make install
 - cd ..
   # Install Cap'n Proto
 - curl -O https://capnproto.org/capnproto-c++-0.7.0.tar.gz
 - tar xvf capnproto-c++-0.7.0.tar.gz
 - cd capnproto-c++-0.7.0
 - ./configure --prefix=/usr/local CPPFLAGS=-DPIC CFLAGS=-fPIC CXXFLAGS=-fPIC LDFLAGS=-fPIC --disable-shared --enable-static
 - make
 - sudo make install
 - cd ..
 - git clone https://github.com/commaai/c-capnproto.git
 - cd c-capnproto
 - git submodule update --init --recursive
 - autoreconf -f -i -s
 - CFLAGS="-fPIC" ./configure --prefix=/usr/local
 - make
 - sudo make install
 - cd ..
   # Clone openpilot
 - git clone https://github.com/commaai/openpilot.git

install:
 - cd openpilot_tools
   # sudo pip install if not using a venv
 - pip install -r requirements.txt
 - pip install -r ../requirements_openpilot.txt
